# Generated by Django 2.0.2 on 2021-10-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180330_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='adress',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='地址'),
        ),
    ]
