# Generated by Django 2.0.2 on 2021-10-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211015_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='adress',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='地址'),
        ),
    ]
